/**
 * The production database is PostgreSQL, but local development and the tests use SQLite. Prisma needs the
 * database type written into the schema file, so the PostgreSQL schema is made from the SQLite one by
 * changing that single line. This keeps the two from drifting apart.
 */
export const POSTGRES_HEADER =
  '// GENERATED from schema.prisma by `npm run db:pg-schema`. Do not edit this file: change schema.prisma instead.\n';

export function toPostgresSchema(sqliteSchema: string) {
  const provider = /provider\s*=\s*"sqlite"/;
  if (!provider.test(sqliteSchema)) throw new Error('schema.prisma no longer uses the "sqlite" provider.');
  return POSTGRES_HEADER + sqliteSchema.replace(provider, 'provider = "postgresql"');
}
